name: illume_app
description: illume is a social networking app for connecting workers.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0-SNAPSHOT

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  # State management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  # Assets
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0
  image_picker: ^0.7.3
  # Localization
  intl: ^0.17.0
  # Business logic
  fuzzy: ^0.4.0-nullsafety.0
  url_launcher: ^6.0.3
  share: ^2.0.1
  # firebase_core: ^1.0.0
  # firebase_auth: ^1.0.0
  # SDK
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.2
  bloc_test: ^8.0.0
#  integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
#  flutter_driver:
#    sdk: flutter

# Flutter specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/sample/
