name: illume_app
description: illume is a new professional social media app for connecting with people who work from home.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0-SNAPSHOT

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  bloc: ^7.0.0-nullsafety.0
  flutter_bloc: ^7.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.1
  intl: ^0.17.0-nullsafety.2
  flutter_svg: ^0.20.0-nullsafety.3
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.0-nullsafety.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# Flutter specific configuration
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/
    - assets/example/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/font/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/font/Quicksand/static/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto/Roboto-Bold.ttf
          weight: 700
